# ВВЕДЕНИЕ В ВЫСШУЮ МАТЕМАТИКУ
****************

## Практическое задание к `Уроку 5`

In [2]:
import pandas as pd
import numpy as np
from numpy import (pi,sin,arcsin,cos,arccos,tan,sqrt,exp)
import math
import matplotlib.pyplot as plt
from pylab import *
from scipy.optimize import fsolve
import warnings
# warnings.filterwarnings('ignore')
%matplotlib inline

### Задание 0
Проверка свойств сложения и умножения матриц

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 12]], float)
B = A * 2
C = B+2/4
k = 2
l = 3

$(k\cdot l)\cdot A = k \cdot (l\cdot A)$

In [33]:
print(np.equal((k*l)*A, k*(l*A)))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


$k\cdot (A+B)=k\cdot A+k\cdot B$

In [15]:
k*(A+B) == k*A+k*B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

$(k+l)\cdot A=k\cdot A+l\cdot A$

In [17]:
(k+l)*A == k*A+l*A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

$(A\cdot B)\cdot C=A\cdot (B\cdot C)$

In [19]:
(A*B)*C == A*(B*C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

$(A+B)\cdot C = A\cdot C+B\cdot C$

In [20]:
(A+B)*C == A*C+B*C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

$A\cdot (B+C)=A\cdot B+A\cdot C$

In [21]:
A*(B+C) == A*B+A*C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Задание 1
- 1. Вектор - это частный случай матрицы 1xN и Nx1.
Повторите материал для векторов, уделяя особое внимание умножению $A\cdot B$.

In [54]:
a = A.reshape(1,-1)
b = B.reshape(-1,1)
c = a*2
print(a)
print()
print(b)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.  0. -1. 12.]]

[[ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]
 [12.]
 [14.]
 [16.]
 [18.]
 [ 0.]
 [-2.]
 [24.]]


In [48]:
print(np.equal((k*l)*a, k*(l*a)))

[[ True  True  True  True  True  True  True  True  True  True  True  True]]


In [45]:
k*(a+b) == k*a+k*b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True

In [50]:
(k+l)*a == k*a+l*a

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

In [55]:
(a*b)*c == a*(b*c)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True

In [82]:
v1 = (k+l)*a
v2 = k*(a+b)
v3 = k*a+l*a
v4 = a*(b+c)
print(f'v1: {v1.shape}\nv2: {v2.shape}\nv3: {v3.shape}\nv4: {v4.shape}')

v1: (1, 12)
v2: (12, 12)
v3: (1, 12)
v4: (12, 12)


- 2. Вычислите, по возможности не используя программирование: $(5E)^{-1}$. E - единичная матрица размера 5х5.

В единичной матрице только главные элементы имеют значения 1, остальные равны 0. Соответственно при умножении на 5, изменятся только элементы главной диагонали. Соответственно, чтобы получить снова единичную матрицу при умножении на обратную, произведение элементов главной диагонали должно быть равно 1, поэтому главнвые элементы обратной матрицы будут равны 1/5. 

In [79]:
np.linalg.inv(5*np.identity(5))

array([[ 0.2,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. ,  0. ],
       [-0. , -0. , -0. ,  0.2, -0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])

### Задание 2

Вычислите определитель (на листочке)

$ detA = \begin{vmatrix}1 & 2 & 3 \\ 4 & 0 & 6 \\ 7 & 8 & 9\end{vmatrix} = 1 \begin{vmatrix} 0 & 6 \\ 8 & 9\end{vmatrix} - 2 \begin{vmatrix} 4 & 7 \\ 6 & 9\end{vmatrix} + 3 \begin{vmatrix} 4 & 7 \\ 0 & 8\end{vmatrix} =$

$ = 1(0 - 48) - 2(36 - 42) + 3(32 - 0) = - 48 + 12 + 96 = 60$

In [91]:
b = np.array([[1,2,3], [4,0,6],[7,8,9]])
np.linalg.det(b)

59.999999999999986

### Задание 3

In [174]:
4*8-7*0

32

- Вычислите матрицу, обратую данной:
$ \begin{vmatrix}1 & 2 & 3 \\ 4 & 0 & 6 \\ 7 & 8 & 9\end{vmatrix} $

$ M_{11} = \begin{vmatrix} 0 & 6 \\ 8 & 9\end{vmatrix} = -48 \quad $
$ M_{12} = \begin{vmatrix} 4 & 6 \\ 7 & 9\end{vmatrix} = -6 \quad$
$ M_{13} = \begin{vmatrix} 4 & 0 \\ 7 & 8\end{vmatrix} = 32 \quad$
$ M_{21} = \begin{vmatrix} 2 & 3 \\ 8 & 9\end{vmatrix} = -6 \quad$
$ M_{22} = \begin{vmatrix} 1 & 3 \\ 7 & 9\end{vmatrix} = -12 \quad $

$ M_{23} = \begin{vmatrix} 1 & 2 \\ 7 & 8\end{vmatrix} = -6 \quad$
$ M_{31} = \begin{vmatrix} 2 & 3 \\ 0 & 6\end{vmatrix} = 12 \quad$
$ M_{32} = \begin{vmatrix} 1 & 4 \\ 3 & 6\end{vmatrix} = -6 \quad$
$ M_{33} = \begin{vmatrix} 1 & 2 \\ 4 & 0\end{vmatrix} = -8 $

$ A_* = \begin{vmatrix} -48 & 6 & 32 \\ 6 & -12 & 6 \\ -12 & 6 & -8\end{vmatrix} \qquad $
$ A_*^T = \begin{vmatrix} -48 & 6 & -12 \\ 6 & -12 & 6 \\ 32 & 6 & -8\end{vmatrix} $

$ A_*^T = \begin{vmatrix} -48 & 6 & -12 \\ 6 & -12 & 6 \\ 32 & 6 & -8\end{vmatrix} \qquad detA = 60 \qquad$
$A^{-1}=A_*^T/detA$

In [175]:
A = np.array([[1,2,3], [4,0,6],[7,8,9]])
A_T = np.array([[-48,6,-12], [6,-12,6],[32,6,-8]])
inv_A = np.linalg.inv(a)

In [176]:
print(inv_A)
print()
print(A_T/np.linalg.det(A))

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]

[[-0.8         0.1        -0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


- Приведите пример матрицы 4х4, ранг которой равен 1

In [167]:
B  = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
np.linalg.matrix_rank(B)

1

In [168]:
B

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

### Задание 4

Вычислить скалярное произведение двух векторов a = (1, 5); b = (2, 8)

$\overline a \cdot \overline b = a_x \cdot b_x + a_y \cdot b_y = 1\cdot 2 + 5\cdot 8 = 42$

In [179]:
a = np.array([1,5])
b = np.array([2,8])
np.dot(a,b)

42

### Задание 5

Вычислить смешанное произведение трех векторов
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [181]:
a = np.array([1,5,0])
b = np.array([2,8,7])
c = np.array([7,1.5,3])

In [187]:
v = np.dot(np.cross(a,b),c)
w = np.dot(a,np.cross(b,c))
print(f'v: {v}\nw: {w}')

v: 228.5
w: 228.5
