# ВВЕДЕНИЕ В ВЫСШУЮ МАТЕМАТИКУ
****************

## Практическое задание к `Уроку 8`

##### Тема “Система линейных алгебраичсеких уравнений”

In [2]:
import pandas as pd
import numpy as np
import scipy
from numpy import (pi,sin,arcsin,cos,arccos,tan,sqrt,exp)
import math
import matplotlib.pyplot as plt
from pylab import *
from scipy.optimize import fsolve
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

##### 1. Решите линейную систему:

$\left[\begin{array}{ccc} 1 && 2 && 3\\4 && 0 && 6\\7 && 8 && 9\end{array}\right]\; \cdot X = \left[\begin{array}{ccc}12\\2\\1\end{array}\right]\;$

In [4]:
A1 = np.array([[1., 2., 3.], [4., 0., 6.], [7., 8., 9.]])
b1 = np.array([12., 2., 1.])
np.linalg.solve(A1, b1)

array([-9.2       ,  0.9       ,  6.46666667])

###### 2. Найдите псевдорешение:
$ x + 2y – z = 1 \\
3x – 4y = 7 \\
8x – 5y + 2z = 12 \\
2x – 5z = 7 \\
11x +4y – 7z = 15 $ 

In [7]:
A2 = np.array([[1, 2, 1], [3, 4, 0], [8, 5, 2], [2, 0, 5], [11, 4, 7]])
B2 = np.array([[1, 2, 1, 1], [3, 4, 0, 7], [8, 5, 2, 12], [2, 0, 5, 7], [11, 4, 7, 15]])
b2 = np.array([1, 7, 12, 7, 15])

In [8]:
print(f'ранг основной матрицы {np.linalg.matrix_rank(A2)}')
print(f'ранг расширенной матрицы {np.linalg.matrix_rank(B2)}')
print('Система линейных уравнений несовместна')

ранг основной матрицы 3
ранг расширенной матрицы 4
Система линейных уравнений несовместна


In [12]:
Q2 =  np.linalg.lstsq(A2, b2)
Q2[0]

array([0.50156212, 1.07281903, 0.88512377])

In [14]:
# Решение через линейную редукцию
R2 = np.dot(np.linalg.inv(np.dot(A2.T, A2)),A2.T)
np.dot(R2, b2)

array([0.50156212, 1.07281903, 0.88512377])

##### 3. Сколько решений имеет линейная система: 

$\left[\begin{array}{ccc} 1 && 2 && 3\\4 && 0 && 6\\7 && 8 && 9\end{array}\right]\; \cdot X = \left[\begin{array}{ccc}12\\2\\1\end{array}\right]\;$

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [18]:
A3 = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B3 = np.array([[1, 2, 3, 12], [4, 0, 6, 2], [7, 8, 9, 1]])
b3 = np.array([12, 2, 1])

In [19]:
print(f'ранг основной матрицы {np.linalg.matrix_rank(A3)}')
print(f'ранг расширенной матрицы {np.linalg.matrix_rank(B3)}')
print('Система линейных уравнений совместна')

ранг основной матрицы 3
ранг расширенной матрицы 3
Система линейных уравнений совместна


In [20]:
np.linalg.solve(A3, b3)

array([-9.2       ,  0.9       ,  6.46666667])

##### 4. Вычислите LU-разложение матрицы:


$\left[\begin{array}{ccc} 1 && 2 && 3\\2 && 16 && 21\\4 && 28 && 73\end{array}\right]\;$ 
 
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [115]:
A4 = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [136]:
L = np.array([[1., 2., 3.], [2., 16., 21.], [4., 28., 73.]])
L[1] = L[1]+L[0]*(-L[1,0])
L[2] = L[2] + L[0]*(-L[2,0])
L[2] = L[2] + L[1]*(-L[2,1]/L[1,1])

U = np.array([[1., 2., 3.], [2., 16., 21.], [4., 28., 73.]])
U[1] = U[1]+U[2]*(-U[1,2]/U[2,2])
U[0] = U[0] + U[2]*(-U[0,2]/U[2,2])
U[0] = U[0] + U[1]*(-U[0,1]/U[1,1])

print(f'L\n{L}\n\nU\n{U}')

L
[[ 1.  2.  3.]
 [ 0. 12. 15.]
 [ 0.  0. 36.]]

U
[[ 0.74482759  0.          0.        ]
 [ 0.84931507  7.94520548  0.        ]
 [ 4.         28.         73.        ]]


##### LU-разложение с помощью модуля scipy:

In [119]:
P4, L4, U4 = scipy.linalg.lu(A4)
print(f'P:\n {P4}\nL:\n {L4}\nU:\n {U4}')

P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U:
 [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [117]:
def gauss(x): # полезные материалы https://slemeshevsky.github.io/python-num-pde/term1/build/html/_sles/gauss.html#sles-lu
    x = np.array(x,float)
    return x[1:]/x[0]

def gauss_app(C, t):
    C = np.array(C, float)
    t = np.array([[t[i]] for i in range(len(t))], float)
    C[1:,:] = C[1:,:] - t*C[0,:]
    return C
def lu(A):
    LU = np.array(A, float)
    for k  in range(LU.shape[0]-1):
        t = gauss(LU[k:, k])
        LU[k+1:,k] = t
        LU[k:, k+1:] = gauss_app(LU[k:, k+1:], t)
    return LU

def solve_lu(A, b):
    LU = lu(A)
    b = np.array(b,float)
    for i in range(1,len(b)):
        b[i] = b[i] - np.dot(LU[i,:i],b[:i])
    for i in range(len(b)-1, -1, -1):
        b[i] = (b[i] - np.dot(LU[i,i+1:],b[i+1:]))/LU[i,i]
    return b

In [118]:
b4 = np.array([4, 39, 105])
solve_lu(A4, b4)

array([-1.68518519,  1.28703704,  1.03703704])

##### 5. Найдите нормальное псевдорешение недоопределенной системы:
$x + 2y – z = 1 \\
8x – 5y + 2z = 12$

Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [9]:
A5 = np.array([[1., 2., 1.], [8., 5., 2.]])
b5 = np.array([1., 12.])
Q5 =  np.linalg.lstsq(A5, b5)
Q5[0]

array([ 1.70253165, -0.21518987, -0.2721519 ])

##### 6. Найдите одно из псевдорешений вырожденной системы:

$\left[\begin{array}{ccc} 1 && 2 && 3\\4 && 5 && 6\\7 && 8 && 9\end{array}\right]\; \cdot X = \left[\begin{array}{ccc}2\\5\\11\end{array}\right]\;$
   
Попробуйте также отыскать и нормальное псевдорешение.

In [8]:
A6 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
b6 = np.array([2., 5., 11.])
Q6 =  np.linalg.lstsq(A6, b6)
Q6[0]

array([ 1.25,  0.5 , -0.25])